spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview_me
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    com.interviewme: DEBUG
    org.springframework.security: DEBUG
