services:

  interview-me-db:
    image: pgvector/pgvector:pg18
    container_name: interview_me_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview_me
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - interview-me-db_pg_data_local:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  interview-me-db_pg_data_local:
    driver: local
